// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDAvzySqdglIwhCkschzFJUiPO6PMCno',
    appId: '1:710303932161:web:08b82b04957d9d51a38500',
    messagingSenderId: '710303932161',
    projectId: 'chatapp-dade8',
    authDomain: 'chatapp-dade8.firebaseapp.com',
    storageBucket: 'chatapp-dade8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhXgfp9M9ivJCH7XHGrO1ZMIj7Wiwr-do',
    appId: '1:710303932161:android:f45d62df1e6f2c79a38500',
    messagingSenderId: '710303932161',
    projectId: 'chatapp-dade8',
    storageBucket: 'chatapp-dade8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbybjFPBOljWrHpkdHXY-zTGUNUbvnOU',
    appId: '1:710303932161:ios:771bb5f147f47f70a38500',
    messagingSenderId: '710303932161',
    projectId: 'chatapp-dade8',
    storageBucket: 'chatapp-dade8.appspot.com',
    iosClientId: '710303932161-ikm686c4826b89fjo5ach2lhs40lo6ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbybjFPBOljWrHpkdHXY-zTGUNUbvnOU',
    appId: '1:710303932161:ios:b43c5cbb69d4f3e1a38500',
    messagingSenderId: '710303932161',
    projectId: 'chatapp-dade8',
    storageBucket: 'chatapp-dade8.appspot.com',
    iosClientId: '710303932161-o298fue1kjqnqlmf2s80hbsc3nqqf5mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
